<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoctor-maven-tools</artifactId>
        <version>3.2.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-maven-commons</artifactId>
    <version>3.2.0-lineaje-01</version>
    <packaging>jar</packaging>

    <name>Asciidoctor Maven Commons</name>
    <description>
        Common components for Asciidoctor Maven Plugin and Asciidoctor Doxia Module(s).
        These should not depend on Doxia libraries, only shared Maven dependencies used by
        all and provided as runtime.
        This is an internal library, backward compatibility is not guaranteed.
    </description>
    <url>https://github.com/asciidoctor/asciidoctor-maven-plugin</url>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.java.version>11</project.java.version>
        <maven.version>3.9.9</maven.version>
        <doxia.version>2.0.0</doxia.version>
        <doxia.sitetools.version>2.0.0</doxia.sitetools.version>
        <plexus-component-metadata.version>2.2.0</plexus-component-metadata.version>
        <plexus-utils.version>3.6.0</plexus-utils.version>
        <asciidoctorj.version>3.0.0</asciidoctorj.version>
        <jruby.version>9.4.12.0</jruby.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>5.12.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>



    <dependencies>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj</artifactId>
            <version>${asciidoctorj.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-core</artifactId>
            <version>3.9.16</version>
            <scope>provided</scope>
        </dependency>
        <!-- Required: see https://issues.apache.org/jira/browse/MNG-6965 -->
        <dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-utils</artifactId>
            <version>${plexus-utils.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.doxia</groupId>
            <artifactId>doxia-core</artifactId>
            <version>${doxia.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.doxia</groupId>
            <artifactId>doxia-sink-api</artifactId>
            <version>${doxia.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>
